# Generated by Django 4.0.3 on 2022-04-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_profile_fburl_profile_igurl_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='filecon',
            field=models.FileField(blank=True, null=True, upload_to='user_post_files'),
        ),
    ]
